# branches to build
branches:
  # whitelist
  only:
    - master

# Operating system (build VM template)
os:
  - Visual Studio 2017
  #- Visual Studio 2015
  #- Visual Studio 2013


configuration:
  - Release
  - Debug

platform:
  - x86
  - x64
  - Any CPU

artifacts:
  - path: output/Dependencies.zip
    name: Dependencies

build:
  project: C:/projects/dependencies/Dependencies.sln


test_script:
  - mkdir output
  - cd output
  - set BINPATH=C:/projects/dependencies/Dependencies/bin/%configuration%
  - 7z a Dependencies.zip %BINPATH%/*.dll %BINPATH%/*.exe
  - powershell Get-ChildItem -Recurse
