# branches to build
branches:
  # whitelist
  only:
    - master

# Operating system (build VM template)
os:
  - Visual Studio 2017
  - Visual Studio 2015
  - Visual Studio 2013


configuration:
  - Release
  - Debug

platform:
  - x86
  - x64
  - Any CPU

build:
  project: C:/projects/dependencies/Dependencies.sln
