# branches to build
branches:
  # whitelist
  only:
    - master

# Operating system (build VM template)
os:
  - Visual Studio 2017
  #- Visual Studio 2015
  #- Visual Studio 2013


configuration:
  - Release
  - Debug

platform:
  - x86
  - x64
  - Any CPU

artifacts:
  - path: output/Dependencies.zip
    name: Dependencies

deploy:
  # Deploy to GitHub Releases
  - provider: GitHub
    artifact: Dependencies
    draft: false
    prerelease: false
    on:
      branch: master                # release from master branch only
      platform: Any CPU
      appveyor_repo_tag: true       # deploy on tag push only


build:
  project: C:/projects/dependencies/Dependencies.sln


test_script: # should be on_finish, but it need to be executed before artifacts is
  - ps: |
      if ( $($env:platform) -eq "Any CPU") {
        New-Item -ItemType Directory -Force -Path "output";
        cd output;

        $BINPATH="C:/projects/dependencies/bin/$($env:CONFIGURATION)AnyCPU";
        $PEVIEW_BIN="C:/projects/dependencies/bin/$($env:CONFIGURATION)64";

        &7z.exe a Dependencies.zip $BINPATH/*.dll $BINPATH/*.exe $PEVIEW_BIN/*.exe
      }
  - ps: Write-Host "Building artifact done"